import ParseItExamples.JSON

#guard JSON.validate "null"
#guard JSON.validate " true "
#guard JSON.validate "0"
#guard JSON.validate "-12.5e+3"
#guard JSON.validate "\"a \\\"quoted\\\" \\u00e9 string\""
#guard JSON.validate "[]"
#guard JSON.validate "[ ]"
#guard JSON.validate "{}"
#guard JSON.validate "{ }"
#guard JSON.validate "[1, [2, [3]], {\"a\": null}]"
#guard JSON.validate "{\"name\": \"ParseIt\", \"deps\": [], \"total\": true, \"n\": 3.14}"
#guard !JSON.validate ""
#guard !JSON.validate "01"
#guard !JSON.validate "1."
#guard !JSON.validate "[1, 2,]"
#guard !JSON.validate "{\"a\" 1}"
#guard !JSON.validate "\"unterminated"
#guard !JSON.validate "\"bad \\x escape\""
#guard !JSON.validate "tru"
#guard !JSON.validate "[1] 2"
